### PR TITLE
Fix Clippy + comments from previous PR

### LINKED ISSUE #21: fix clippy issues
currently CI seems to be failing, would be nice to fix that!

### PR DESCRIPTION
**Pull request by RedaOps**
Hey there! Reviewed and changed some stuff we talked about in #18 . Also fixed clippy and ran a workflow locally and it's looking good now!

Haven't tested these new changes, but I have not modified any functionality whatsoever. The e2e testing pipeline we were talking about is going to be really useful.

closes #21

### CODE REVIEW

**Comment by RedaOps** [comment]
closes #21

File: src/committee/orchestrator.rs [hunk 1]
```diff
@@ -347,17 +335,25 @@ impl Orchestrator {
...
                         continue 'retry;
                     }
                 };
 
-                let response: bitcoincore_rpc::jsonrpc::Response = serde_json::from_str(&resp)?;
-                let resp: Round1Response = response.result()?;
+                if let Ok(response) =
+                    serde_json::from_str::<bitcoincore_rpc::jsonrpc::Response>(&resp)
+                {
+                    let resp: Round1Response = response.result()?;
```
[the remark this answers is not in the document]
Comment (mimoo) [reply src/committee/orchestrator.rs:347]: I'm wondering if it would be cleaner to do something like this:

```rust
let res = resp.map_err(|e| format!("connection error: {e}").and_then(|r| serde_json::from_str::< bitcoincore_rpc::jsonrpc::Response>(&r).map_err(|e| format!("json error: {e}"))).and_then(|r| r.result().map_err(|e| format!("rpc error: {e}")));
let resp = match res {
  Ok(x) => x,
  Err(e) => {
     warn!("Round 1 error with {addr}: {e}", addr=member.address);
     self.member_status.write().unwrap().mark_as_disconnected(member_id);
     need_retry = true // since at this point we have waiting for all the response might as well check all of them before retrying (so that we potentially discover multiple disconnects?)
  }
}
```

File: src/committee/orchestrator.rs [hunk 2]
```diff
@@ -402,17 +398,25 @@ impl Orchestrator {
...
                         continue 'retry;
                     }
                 };
 
-                let response: bitcoincore_rpc::jsonrpc::Response = serde_json::from_str(&resp)?;
-                let round2_response: Round2Response = response.result()?;
+                if let Ok(response) =
+                    serde_json::from_str::<bitcoincore_rpc::jsonrpc::Response>(&resp)
+                {
+                    let round2_response: Round2Response = response.result()?;
```
Comment (mimoo) [inline src/committee/orchestrator.rs:410]: same here

File: src/committee/orchestrator.rs [hunk 3]
```diff
@@ -578,13 +578,11 @@ pub async fn run_server(
...
-            pubkey_package,
-            committee_cfg,
-        },
-        member_status_state.clone(),
-    );
+    let ctx = Orchestrator {
+        pubkey_package,
+        committee_cfg,
+        member_status: member_status_state,
+    };
```
Comment (mimoo) [inline src/committee/orchestrator.rs:585]: perhaps it would be cleaner to do a `let ctx = Orchestrator::new(pubkey_package, committee_cfg)` and take care of creating the `member_status_state` there

File: .github/workflows/rust.yml [hunk 4]
```diff
@@ -100,4 +100,4 @@ jobs:
         uses: actions-rs/cargo@v1
         with:
           command: clippy
-          args: --all-features -- -D warnings
+          args: --all-features -- -D warnings -A clippy::absurd_extreme_comparisons
```
Comment (mimoo) [inline .github/workflows/rust.yml:103]: better to add `#[allow(clippy::absurd_Extreme_comparisons)]` next to where the the warning is being given :o

**Review by mimoo — APPROVED** [review]
Awesome! Thanks for the PR :) left some random thoughts

File: src/committee/orchestrator.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (RedaOps) [reply src/committee/orchestrator.rs:347]: Yep, saw that. We won't even need the `response.result()?` part once we have a custom serde struct for Node RPC responses. I can open up an issue for this, but would rather fix this after we have at least *some* e2e tests so I can just run the job and make sure I don't broken anything by accident, without having to recreate the whole environment each time.

File: src/committee/orchestrator.rs (hunk 3 above)
Comment (RedaOps) [reply src/committee/orchestrator.rs:585]: Yup

File: .github/workflows/rust.yml (hunk 4 above)
Comment (RedaOps) [reply .github/workflows/rust.yml:103]: Yup, tried that but there were some issues with the `ensure!` macro where most absurd checks are being done. For some reason clippy ignored the decoration.
